version: '3'

services:

  app:
    image: cristianodewes/node-app
    container_name: node-app
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  db:
    image: cristianodewes/node-db
    command: --innodb-use-native-aio=0
    container_name: node-db
    restart: always
    tty: true
    networks:
      - node-network

  nginx:
    image: cristianodewes/node-nginx
    container_name: node-nginx
    tty: true
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge